name: Reusable Upload Artifacts

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      path:
        required: true
        type: string
      os:
        required: false
        type: string
        default: ubuntu-latest

permissions:
  contents: read

jobs:
  upload-artifacts:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.path }}
          if-no-files-found: warn
